// Stub header for unit tests — declares the Go Wallet SDK C API.
// The real header is generated by CGo during the Go build and placed at lib/.
// This stub allows tests to compile against mock_gowalletsdk.cpp.

#ifndef LIBGOWALLETSDK_H
#define LIBGOWALLETSDK_H

#include <stdint.h>

typedef unsigned long long GoWSKHandle;

void GoWSK_FreeCString(char* str);

// Keystore
GoWSKHandle GoWSK_accounts_keystore_NewKeyStore(const char* dir, int scryptN, int scryptP, char** error);
void GoWSK_accounts_keystore_CloseKeyStore(GoWSKHandle handle);
char* GoWSK_accounts_keystore_Accounts(GoWSKHandle handle, char** error);
char* GoWSK_accounts_keystore_NewAccount(GoWSKHandle handle, const char* passphrase, char** error);
char* GoWSK_accounts_keystore_Import(GoWSKHandle handle, const char* keyJSON, const char* passphrase, const char* newPassphrase, char** error);
char* GoWSK_accounts_keystore_Export(GoWSKHandle handle, const char* address, const char* passphrase, const char* newPassphrase, char** error);
void GoWSK_accounts_keystore_Delete(GoWSKHandle handle, const char* address, const char* passphrase, char** error);
int GoWSK_accounts_keystore_HasAddress(GoWSKHandle handle, const char* address, char** error);
void GoWSK_accounts_keystore_Unlock(GoWSKHandle handle, const char* address, const char* passphrase, char** error);
void GoWSK_accounts_keystore_Lock(GoWSKHandle handle, const char* address, char** error);
void GoWSK_accounts_keystore_TimedUnlock(GoWSKHandle handle, const char* address, const char* passphrase, unsigned long timeout, char** error);
void GoWSK_accounts_keystore_Update(GoWSKHandle handle, const char* address, const char* passphrase, const char* newPassphrase, char** error);
char* GoWSK_accounts_keystore_SignHash(GoWSKHandle handle, const char* address, const char* hashHex, char** error);
char* GoWSK_accounts_keystore_SignHashWithPassphrase(GoWSKHandle handle, const char* address, const char* passphrase, const char* hashHex, char** error);
char* GoWSK_accounts_keystore_ImportECDSA(GoWSKHandle handle, const char* privateKeyHex, const char* passphrase, char** error);
char* GoWSK_accounts_keystore_SignTx(GoWSKHandle handle, const char* address, const char* txJSON, const char* chainIDHex, char** error);
char* GoWSK_accounts_keystore_SignTxWithPassphrase(GoWSKHandle handle, const char* address, const char* passphrase, const char* txJSON, const char* chainIDHex, char** error);
char* GoWSK_accounts_keystore_Find(GoWSKHandle handle, const char* address, const char* url, char** error);

// Extended Keystore
GoWSKHandle GoWSK_accounts_extkeystore_NewKeyStore(const char* dir, int scryptN, int scryptP, char** error);
void GoWSK_accounts_extkeystore_CloseKeyStore(GoWSKHandle handle);
char* GoWSK_accounts_extkeystore_Accounts(GoWSKHandle handle, char** error);
char* GoWSK_accounts_extkeystore_NewAccount(GoWSKHandle handle, const char* passphrase, char** error);
char* GoWSK_accounts_extkeystore_Import(GoWSKHandle handle, const char* keyJSON, const char* passphrase, const char* newPassphrase, char** error);
char* GoWSK_accounts_extkeystore_ImportExtendedKey(GoWSKHandle handle, const char* extKeyStr, const char* passphrase, char** error);
char* GoWSK_accounts_extkeystore_ExportExt(GoWSKHandle handle, const char* address, const char* passphrase, const char* newPassphrase, char** error);
char* GoWSK_accounts_extkeystore_ExportPriv(GoWSKHandle handle, const char* address, const char* passphrase, const char* newPassphrase, char** error);
void GoWSK_accounts_extkeystore_Delete(GoWSKHandle handle, const char* address, const char* passphrase, char** error);
int GoWSK_accounts_extkeystore_HasAddress(GoWSKHandle handle, const char* address, char** error);
void GoWSK_accounts_extkeystore_Unlock(GoWSKHandle handle, const char* address, const char* passphrase, char** error);
void GoWSK_accounts_extkeystore_Lock(GoWSKHandle handle, const char* address, char** error);
void GoWSK_accounts_extkeystore_TimedUnlock(GoWSKHandle handle, const char* address, const char* passphrase, unsigned long timeout, char** error);
void GoWSK_accounts_extkeystore_Update(GoWSKHandle handle, const char* address, const char* passphrase, const char* newPassphrase, char** error);
char* GoWSK_accounts_extkeystore_SignHash(GoWSKHandle handle, const char* address, const char* hashHex, char** error);
char* GoWSK_accounts_extkeystore_SignHashWithPassphrase(GoWSKHandle handle, const char* address, const char* passphrase, const char* hashHex, char** error);
char* GoWSK_accounts_extkeystore_SignTx(GoWSKHandle handle, const char* address, const char* txJSON, const char* chainIDHex, char** error);
char* GoWSK_accounts_extkeystore_SignTxWithPassphrase(GoWSKHandle handle, const char* address, const char* passphrase, const char* txJSON, const char* chainIDHex, char** error);
char* GoWSK_accounts_extkeystore_Derive(GoWSKHandle handle, const char* address, const char* derivationPath, int pin, char** error);
char* GoWSK_accounts_extkeystore_DeriveWithPassphrase(GoWSKHandle handle, const char* address, const char* derivationPath, int pin, const char* passphrase, const char* newPassphrase, char** error);
char* GoWSK_accounts_extkeystore_Find(GoWSKHandle handle, const char* address, const char* url, char** error);

// Key operations
char* GoWSK_accounts_keys_CreateExtKeyFromMnemonic(const char* phrase, const char* passphrase, char** error);
char* GoWSK_accounts_keys_DeriveExtKey(const char* extKeyStr, const char* pathStr, char** error);
char* GoWSK_accounts_keys_ExtKeyToECDSA(const char* extKeyStr, char** error);
char* GoWSK_accounts_keys_ECDSAToPublicKey(const char* privateKeyStr, char** error);
char* GoWSK_accounts_keys_PublicKeyToAddress(const char* publicKeyStr, char** error);

// Mnemonic operations
char* GoWSK_accounts_mnemonic_CreateRandomMnemonic(int length, char** error);
char* GoWSK_accounts_mnemonic_CreateRandomMnemonicWithDefaultLength(char** error);
uint32_t GoWSK_accounts_mnemonic_LengthToEntropyStrength(int length, char** error);

#endif // LIBGOWALLETSDK_H
